"""
Prompt templates for QA Voice Agent analysis.
"""

from .classification_prompts import (
    PRIMARY_CLASSIFICATION_PROMPT,
    INTENT_RECOGNITION_PROMPT,
    SUCCESS_METRICS_PROMPT,
    FAILURE_ANALYSIS_PROMPT,
    COMPARATIVE_ANALYSIS_PROMPT,
    CUSTOM_BUSINESS_PROMPT,
)

__all__ = [
    "PRIMARY_CLASSIFICATION_PROMPT",
    "INTENT_RECOGNITION_PROMPT",
    "SUCCESS_METRICS_PROMPT",
    "FAILURE_ANALYSIS_PROMPT",
    "COMPARATIVE_ANALYSIS_PROMPT",
    "CUSTOM_BUSINESS_PROMPT",
]